# Generated by Django 4.1.3 on 2023-02-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0005_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencias'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
                ('aviso', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False, 'ordering': ['-fechahoraimg']},
        ),
    ]
