# Generated by Django 4.1.3 on 2023-02-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0006_contacto_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False, 'ordering': ['-registrarseforo_idregistroforo']},
        ),
    ]
