# Generated by Django 4.1.3 on 2023-02-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0009_contacto_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False},
        ),
    ]
