# Generated by Django 4.1.3 on 2023-03-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0013_contacto_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='AccountEmailaddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailconfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialaccount',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialapp',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialappSites',
        ),
        migrations.DeleteModel(
            name='SocialaccountSocialtoken',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False},
        ),
    ]
