# Generated by Django 4.1.3 on 2023-03-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0014_delete_contacto_delete_accountemailaddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='Modulo1Contacto',
        ),
    ]
