# Generated by Django 4.1.3 on 2023-03-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0020_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
    ]
