# Generated by Django 4.1.3 on 2023-03-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0021_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False, 'ordering': ['-idperfilforo']},
        ),
    ]
