# Generated by Django 4.1.3 on 2023-03-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0027_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False, 'ordering': ['-idperfilforo']},
        ),
    ]
