# Generated by Django 4.1.3 on 2023-03-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0031_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False, 'ordering': ['-idperfilforo']},
        ),
        migrations.AlterModelOptions(
            name='temaforo',
            options={'managed': False, 'ordering': ['-usuario']},
        ),
    ]
