# Generated by Django 4.1.3 on 2023-03-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0032_alter_comentario_options_alter_perfilforo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temaforo',
            options={'managed': False, 'ordering': ['-fecha']},
        ),
    ]
