# Generated by Django 4.1.3 on 2023-03-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0036_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='perfilforo',
            options={'managed': False, 'ordering': ['-idperfilforo']},
        ),
        migrations.AlterModelOptions(
            name='temaforo',
            options={'managed': False, 'ordering': ['-idtemaforo']},
        ),
    ]
