# Generated by Django 4.1.3 on 2023-03-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0045_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False, 'ordering': ['-fechahoracoment']},
        ),
        migrations.AlterModelOptions(
            name='temaforo',
            options={'managed': False, 'ordering': ['-idtemaforo']},
        ),
    ]
