from django.contrib import admin
from modulo1.models import *
from .models import Contacto

# Register your models here.


admin.site.register(Ainsecticida)
admin.site.register(Categoriaforo)
admin.site.register(Comentario)
admin.site.register(Crearhiloforo)
admin.site.register(Enfermedades)
admin.site.register(Foro)
admin.site.register(Gastos)
admin.site.register(Historial)
admin.site.register(Imagen)
admin.site.register(Informacioncafe)
admin.site.register(Insecticidas)
admin.site.register(Inversion)
admin.site.register(Lote)
admin.site.register(Mcontrolenfermedad)
admin.site.register(Mcontrolplagas)
admin.site.register(Pcurativasenfer)
admin.site.register(Pcurativasplaga)
admin.site.register(Perdidas)
admin.site.register(Perfilforo)
admin.site.register(Persona)
admin.site.register(Personainfocafe)
admin.site.register(Plagas)
admin.site.register(Ppreventivaenfer)
admin.site.register(Ppreventivasplaga)
admin.site.register(Reaccionpost)
admin.site.register(Recomendacioninsect)
admin.site.register(Recomendacionplaga)
admin.site.register(Rfinanciero)
admin.site.register(Rfinancierolote)
admin.site.register(Temaforo)
admin.site.register(Tenfermedad)
admin.site.register(Tgastos)
admin.site.register(Tinsecticida)
admin.site.register(Tinversion)
admin.site.register(Tperdida)
admin.site.register(Tpersona)
admin.site.register(Tratamiento)
admin.site.register(Tusuarioforo)
admin.site.register(Tvariedad)
admin.site.register(Valorganancia)
admin.site.register(Valorgasto)
admin.site.register(Valorinversion)
admin.site.register(Valorperdida)
admin.site.register(Variedad)
admin.site.register(Variedadgenetica)
admin.site.register(Vistas)
admin.site.register(Contacto)